#服务器端口
server:
  port: 8107

#数据源配置
spring:
  datasource:
    url: ${ucs.datasource.dev.url}
    username: ${ucs.datasource.dev.username}
    password: ${ucs.datasource.dev.password}


#配置日志
logging:
  #此处存放日志的路径
  path:
    config: classpath:config/logback-spring.xml
  #指定不同目录下的日志的级别
  level:
    com.sailmi.system: DEBUG
